version: '3.9'

services:
  backend:
    container_name: backend-meetsync
    depends_on:
      - postgres
    ports:
      - 8000:8000
    restart: always
    build: ./backend/
  
  background:
    container_name: background-meetsync
    depends_on:
      - backend
    build: ./background/

  frontend:
    container_name: frontend-meetsync
    depends_on:
      - backend
    ports:
      - 80:80
    build: ./frontend/

  postgres:
    container_name: postgres-meetsync
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=someuser
      - POSTGRES_PASSWORD=12345678
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: