version: '3.9'

services:
  backend:
    container_name: backend-meetsync
    depends_on:
      - postgres
    ports:
      - 8080:8080
    build: ./backend/
  
  postgres:
    container_name: postgres-meetsync
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=someuser
      - POSTGRES_PASSWORD=12345678
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: